title: Kexin HUANG
url: "https://kexinhuang19.github.io/"
baseurl: ""

markdown: kramdown
# ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
# footer_url: "https://github.com/ankitsultana"
footer_text: "KexinHUANG©2024"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 # - name: "Resume"
 #   link: "https://github.com/KexinHUANG19/KexinHUANG19.github.io/resume.pdf"

remote_theme: ankitsultana/researcher@gem
plugins:
  - jekyll-remote-theme
