title: Kexin HUANG
url: "https://kexinhuang19.github.io/"
baseurl: "/researcher"

markdown: kramdown
# ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
# footer_url: "https://github.com/ankitsultana"
footer_text: "- Forever Young -"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 # - name: "Resume"
 #   link: "https://github.com/KexinHUANG19/KexinHUANG19.github.io/resume.pdf"

remote_theme: ankitsultana/researcher@gem
